config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :projects do
    resources :donations, only: [:new, :create]
  end

  root 'projects#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/donation.rb
class Donation < ApplicationRecord
  belongs_to :project
  belongs_to :user

  validates :value, numericality: { greater_than: 0 }

  validate :project_is_expired?

  def project_is_expired?
    if project.is_expired?
      errors.add(:project, "project is expired")
    end
  end
end

app/models/project.rb
class Project < ApplicationRecord

  validates :title, presence: true
  validates :description, presence: true
  validates :due_date, presence: true
  validates :target, presence: true
  validates :image, presence: true

  validates :title, length: { maximum: 64 }
  validates :description, length: { maximum: 512 }

  validates :target, numericality: { greater_than: 0 }
  validates :target, numericality: { less_than_or_equal_to: 500 }

  validate :due_date_cannot_be_in_the_past_or_30_days_from_today

  belongs_to :user
  has_many :donations, dependent: :delete_all

  has_one_attached :image

  def due_date_cannot_be_in_the_past_or_30_days_from_today
    if due_date.present? and (due_date < Date.today or due_date > Date.today + 30.days)
      errors.add(:due_date, "can't be in the past or 30 days from today")
    end
  end

  def donators
    Donation.joins(:user).where(project_id: self.id).group('users.id').pluck('users.name').to_sentence
  end

  def total_received
    total = 0
    self.donations.each do |donation|
      total = total + donation.value
    end
    total
  end

  def is_expired?
    due_date.present? and due_date < Date.today
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :projects

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  include Pundit

  rescue_from Pundit::NotAuthorizedError, with: :not_authorized

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  def not_authorized
    redirect_to(root_path)
  end
end

app/controllers/donations_controller.rb
class DonationsController < ApplicationController
  before_action :set_donation, only: [:show, :edit, :update, :destroy]

    # GET /donations/new
  def new
    @donation = Donation.new
    @project = Project.find(params[:project_id])
  end

  # POST /donations
  # POST /donations.json
  def create
    @donation = Donation.new(donation_params)
    @project = Project.find(params[:project_id])
    respond_to do |format|
      if @donation.save
        format.html { redirect_to @project, notice: 'Donation was successfully created.' }
        format.json { render :show, status: :created, location: @donation }
      else
        format.html { render :new }
        format.json { render json: @donation.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_donation
      @donation = Donation.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def donation_params
      params.require(:donation).permit(:project_id, :user_id, :value)
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @q = Project.ransack(params[:q])
    @projects = @q.result(distinct: true)
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
    authorize @project
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    authorize @project
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    authorize @project
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:title, :description, :target, :due_date, :user_id, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/donations_helper.rb
module DonationsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/donations/_form.html.erb
<%= simple_form_for([@project, @donation]) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :project_id, as: :hidden, input_html: {value: @project.id} %>
    <%= f.input :user_id, as: :hidden, input_html: {value: current_user.id} %>
    <%= f.input :value %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: 'btn btn-success' %>
  </div>
<% end %>

app/views/donations/new.html.erb
<h1>New Donation</h1>

<%= render 'form', donation: @donation %>

<%= link_to 'Back', project_path(@project) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </head>

  <body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <%= link_to 'Catarsinho', root_path, class: 'navbar-brand' %>
      <div class="collapse navbar-collapse" id="navbarText">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <% if current_user.present? %>
              <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: 'nav-link' %>
            <% end %>
          </li>
        </ul>
      </div>
    </nav>
    <div class="container">
      <% if notice %>
        <div class="alert alert-success" role="alert">
          <%= notice %>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/projects/_form.html.erb
<%= simple_form_for(@project) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :description %>
    <%= f.input :target %>
    <%= f.input :due_date %>
    <%= f.input :image, type: :file %>
    <%= f.input :user_id, as: :hidden, input_html: {value: current_user.id} %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<h1>Projects</h1>
<hr>
<%= search_form_for @q, html: {class: 'form-inline' } do |f| %>
  <%= f.search_field :title_cont, class: 'form-control', placeholder: 'Title' %>
  <%= f.submit class: 'btn btn-primary' %>

  <div class="dropdown">
    <button class="btn dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      Order
    </button>
    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
      <%= sort_link @q, :title %><br>
      <%= sort_link @q, :target %><br>
      <%= sort_link @q, :due_date %>
    </div>
  </div>
<% end %>

<br>
<div class="row">

  <% @projects.each do |project| %>
    <div class="col-lg-6">
      <div class="card" style="width: 100%">
        <% if project.image.present? %>
          <div class="symbol symbol-50 symbol-lg-120">
            <%= image_tag(url_for(project.image), style: 'height: auto; width: auto; display: block; max-height: 200px; margin-left: auto; margin-right: auto', class: 'card-img-top img-thumbnail') %>
          </div>
        <% end %>
        <div class="card-body">
          <h5 class="card-title"><%= project.title %></h5>
          <p class="card-text"><%= project.description %></p>
          <p class="card-text"><strong>target: </strong> <%= number_to_currency(project.target) %></p>
          <p class="card-text"><strong>Due date: </strong><%= project.due_date.strftime("%d/%m/%Y") %></p>
          <%= link_to 'Visualize', project, class: 'btn btn-primary' %>
          <% if !project.is_expired? %>
            <%= link_to 'Donate', new_project_donation_path(project), class: 'btn btn-success' %>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>
<br>
<%= link_to 'New Project', new_project_path, class: 'btn btn-primary' %>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<h1><%= @project.title %></h1>
<hr>

<% if !@project.is_expired? %>
  <%= link_to 'Donate', new_project_donation_path(@project), class: 'btn btn-success' %>
<% end %>
<br>
<br>

<% if @project.image.present? %>
    <%= image_tag(url_for(@project.image), style: 'height: auto; width: auto; display: block; max-height: 300px; margin-left: auto; margin-right: auto') %>
<% end %>
<br>
<p>
  <strong>Description:</strong>
  <%= @project.description %>
</p>

<p>
  <strong>Target:</strong>
  <%= number_to_currency(@project.target) %>
</p>

<p>
  <strong>Due date:</strong>
  <%= @project.due_date.strftime("%d/%m/%Y") %>
</p>

<p>
  <strong>Total received:</strong>
  <%= number_to_currency(@project.total_received) %>
</p>

<p >
  <strong>Donators:</strong>
  <%= @project.donators %>
</p>

<% if policy(@project).edit? %>
  <%= link_to 'Edit', edit_project_path(@project) %> |
<% end %>
<% if policy(@project).destroy? %>
  <%= link_to 'Destroy', @project, method: :delete, data: { confirm: 'Are you sure?' }, style: 'color: red;' %> |
<% end %>
<%= link_to 'Back', projects_path %>